# Generated by Django 4.0.2 on 2022-02-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.PositiveSmallIntegerField(max_length=250)),
                ('message', models.TextField(max_length=250)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-time', 'read'],
            },
        ),
    ]
