# Generated by Django 4.0.2 on 2022-02-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Name',
            new_name='name',
        ),
    ]
