# Generated by Django 4.0.2 on 2022-02-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_name_message_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['read']},
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
